using LogicBuilder.Forms.Parameters;
using System.Collections.Generic;
using System.Collections.ObjectModel;

namespace LogicBuilder.RulesDirector
{
    public interface IFlowActivity
    {
        /// <summary>
        /// Facilitates ruleset execution
        /// </summary>
        DirectorBase Director
        {
            get;
        }

        /// <summary>
        /// Called by the autogenerated rules when a value contains
        /// a mixture of text, variables and functions
        /// </summary>
        /// <param name="format"></param>
        /// <param name="list"></param>
        /// <returns></returns>
        string FormatString(string format, Collection<object> list);

        /// <summary>
        /// Called by the autogenerated rules when a value contains
        /// a mixture of text, variables and functions
        /// </summary>
        /// <param name="format"></param>
        /// <param name="list"></param>
        /// <returns></returns>
        string FormatString(string format, object[] list);

        /// <summary>
        /// Called by the autogenerated rules when the End Flow shape is current
        /// </summary>
        void FlowComplete();

        /// <summary>
        /// Called by the autogenerated rules when the Terminate Shape is current
        /// </summary>
        void Terminate();

        /// <summary>
        /// Called by the autogenerated rules when the WaitCondition or the WaitDecision conditions evaluate to false
        /// </summary>
        void Wait();

        /// <summary>
        /// Called by the autogenerated rules when the Question List Shape is current
        /// </summary>
        /// <param name="form"></param>
        /// <param name="shortValues"></param>
        void DisplayQuestions(QuestionFormParameters form, ICollection<ConnectorParameters> shortValues = null);

        /// <summary>
        /// Called by the autogenerated rules when the Input Questions Shape is current
        /// </summary>
        /// <param name="form"></param>
        void DisplayInputQuestions(InputFormParameters form, ICollection<ConnectorParameters> shortValues = null);
    }
}
