//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogicBuilder.RulesDirector {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LogicBuilder.RulesDirector.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current module name must be empty {0}..
        /// </summary>
        internal static string currentModuleMustBeEmptyFormat {
            get {
                return ResourceManager.GetString("currentModuleMustBeEmptyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred..
        /// </summary>
        internal static string defaultErrorMessage {
            get {
                return ResourceManager.GetString("defaultErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boolean.
        /// </summary>
        internal static string displayBoolean {
            get {
                return ResourceManager.GetString("displayBoolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Byte.
        /// </summary>
        internal static string displayByte {
            get {
                return ResourceManager.GetString("displayByte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Char.
        /// </summary>
        internal static string displayChar {
            get {
                return ResourceManager.GetString("displayChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateTime.
        /// </summary>
        internal static string displayDateTime {
            get {
                return ResourceManager.GetString("displayDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decimal.
        /// </summary>
        internal static string displayDecimal {
            get {
                return ResourceManager.GetString("displayDecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double.
        /// </summary>
        internal static string displayDouble {
            get {
                return ResourceManager.GetString("displayDouble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guid.
        /// </summary>
        internal static string displayGuid {
            get {
                return ResourceManager.GetString("displayGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Int16.
        /// </summary>
        internal static string displayInt16 {
            get {
                return ResourceManager.GetString("displayInt16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Int32.
        /// </summary>
        internal static string displayInt32 {
            get {
                return ResourceManager.GetString("displayInt32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integer.
        /// </summary>
        internal static string displayInt64 {
            get {
                return ResourceManager.GetString("displayInt64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NullableBoolean.
        /// </summary>
        internal static string displayNullableBoolean {
            get {
                return ResourceManager.GetString("displayNullableBoolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NullableByte.
        /// </summary>
        internal static string displayNullableByte {
            get {
                return ResourceManager.GetString("displayNullableByte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NullableChar.
        /// </summary>
        internal static string displayNullableChar {
            get {
                return ResourceManager.GetString("displayNullableChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NullableDateTime.
        /// </summary>
        internal static string displayNullableDateTime {
            get {
                return ResourceManager.GetString("displayNullableDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NullableDecimal.
        /// </summary>
        internal static string displayNullableDecimal {
            get {
                return ResourceManager.GetString("displayNullableDecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NullableDouble.
        /// </summary>
        internal static string displayNullableDouble {
            get {
                return ResourceManager.GetString("displayNullableDouble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NullableGuid.
        /// </summary>
        internal static string displayNullableGuid {
            get {
                return ResourceManager.GetString("displayNullableGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NullableInt16.
        /// </summary>
        internal static string displayNullableInt16 {
            get {
                return ResourceManager.GetString("displayNullableInt16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NullableInt32.
        /// </summary>
        internal static string displayNullableInt32 {
            get {
                return ResourceManager.GetString("displayNullableInt32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NullableInteger.
        /// </summary>
        internal static string displayNullableInt64 {
            get {
                return ResourceManager.GetString("displayNullableInt64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NullableSByte.
        /// </summary>
        internal static string displayNullableSByte {
            get {
                return ResourceManager.GetString("displayNullableSByte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NullableFloat.
        /// </summary>
        internal static string displayNullableSingle {
            get {
                return ResourceManager.GetString("displayNullableSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NullableTimeSpan.
        /// </summary>
        internal static string displayNullableTimeSpan {
            get {
                return ResourceManager.GetString("displayNullableTimeSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NullableUInt16.
        /// </summary>
        internal static string displayNullableUInt16 {
            get {
                return ResourceManager.GetString("displayNullableUInt16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NullableUInt32.
        /// </summary>
        internal static string displayNullableUInt32 {
            get {
                return ResourceManager.GetString("displayNullableUInt32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NullableUInt64.
        /// </summary>
        internal static string displayNullableUInt64 {
            get {
                return ResourceManager.GetString("displayNullableUInt64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SByte.
        /// </summary>
        internal static string displaySByte {
            get {
                return ResourceManager.GetString("displaySByte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Float.
        /// </summary>
        internal static string displaySingle {
            get {
                return ResourceManager.GetString("displaySingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String.
        /// </summary>
        internal static string displayString {
            get {
                return ResourceManager.GetString("displayString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimeSpan.
        /// </summary>
        internal static string displayTimeSpan {
            get {
                return ResourceManager.GetString("displayTimeSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UInt16.
        /// </summary>
        internal static string displayUInt16 {
            get {
                return ResourceManager.GetString("displayUInt16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UInt32.
        /// </summary>
        internal static string displayUInt32 {
            get {
                return ResourceManager.GetString("displayUInt32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UInt64.
        /// </summary>
        internal static string displayUInt64 {
            get {
                return ResourceManager.GetString("displayUInt64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module: {0}, Page: {1}, Shape Index: {2}..
        /// </summary>
        internal static string flowStatusFormat {
            get {
                return ResourceManager.GetString("flowStatusFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module: {0}..
        /// </summary>
        internal static string flowStatusFormatInitial {
            get {
                return ResourceManager.GetString("flowStatusFormatInitial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get {0} variable {1} failed.  Invalid data: {2}..
        /// </summary>
        internal static string getFailedInvalidDataFormat {
            get {
                return ResourceManager.GetString("getFailedInvalidDataFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get {0} variable {1} failed.  The current type is {2}..
        /// </summary>
        internal static string getFailedInvalidTypeFormat {
            get {
                return ResourceManager.GetString("getFailedInvalidTypeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get {0} variable {1} failed.  Data is null..
        /// </summary>
        internal static string getFailedNullLiteralFormat {
            get {
                return ResourceManager.GetString("getFailedNullLiteralFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get {0} input failed. Index: {1}. Invalid data: {2}..
        /// </summary>
        internal static string getInputFailedInvalidFormat {
            get {
                return ResourceManager.GetString("getInputFailedInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get input failed.  Entry not found. Index: {0}..
        /// </summary>
        internal static string getInputFailedNotFoundFormat {
            get {
                return ResourceManager.GetString("getInputFailedNotFoundFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get {0} resource {1} failed.  Invalid data: {2}..
        /// </summary>
        internal static string getResourceFailedInvalidFormat {
            get {
                return ResourceManager.GetString("getResourceFailedInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get resource {0} for type &quot;{1}&quot; failed. Invalid type..
        /// </summary>
        internal static string getResourceFailedInvalidTypeFormat {
            get {
                return ResourceManager.GetString("getResourceFailedInvalidTypeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get resource {0} failed.  Resource not found..
        /// </summary>
        internal static string getResourceFailedNotFoundFormat {
            get {
                return ResourceManager.GetString("getResourceFailedNotFoundFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegal use of {0}..
        /// </summary>
        internal static string illegalMethodCallFormat {
            get {
                return ResourceManager.GetString("illegalMethodCallFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument is invalid {0}..
        /// </summary>
        internal static string invalidArgumentFormat {
            get {
                return ResourceManager.GetString("invalidArgumentFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module {0} is missing. Reload missing modules and retry your operation..
        /// </summary>
        internal static string moduleNotFoundFormat {
            get {
                return ResourceManager.GetString("moduleNotFoundFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No license found..
        /// </summary>
        internal static string noLicenseFound {
            get {
                return ResourceManager.GetString("noLicenseFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License or license features are not installed. Select BPS Rules/BPS Rules Director/Activate BPS Rules Director from the All Programs menu. {0}..
        /// </summary>
        internal static string noLicenseMessageFormat {
            get {
                return ResourceManager.GetString("noLicenseMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule Execution cannot be null for this operation..
        /// </summary>
        internal static string ruleExecutionCannotBeNull {
            get {
                return ResourceManager.GetString("ruleExecutionCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule set cannot be null for this operation..
        /// </summary>
        internal static string ruleSetCannotBeNull {
            get {
                return ResourceManager.GetString("ruleSetCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set {0} variable {1} failed.  The current type is {2}..
        /// </summary>
        internal static string setFailedInvalidTypeFormat {
            get {
                return ResourceManager.GetString("setFailedInvalidTypeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}).
        /// </summary>
        internal static string variableTypeToStringFormat {
            get {
                return ResourceManager.GetString("variableTypeToStringFormat", resourceCulture);
            }
        }
    }
}
